@echo off

SET PORTAL_ROOTDIR=%CD%\target
SET PORTAL_BASEDIR=%PORTAL_ROOTDIR%\aui-demo
SET PORTAL_WEBAPPS=%PORTAL_BASEDIR%\webapps
SET PORTAL_LOGS=%PORTAL_BASEDIR%\logs
SET PORTAL_NAME=aui-demo-webapp
SET PORTAL_CONTEXT_PATH=/
SET PORTAL_PORT=8080

IF EXIST %PORTAL_ROOTDIR% GOTO CONTINUE
echo You need to build AUI Demo WebApp at first! Please run command 'build.bat' ... >&2
GOTO EXIT

:CONTINUE
IF EXIST %PORTAL_BASEDIR% GOTO STEP1
MKDIR %PORTAL_BASEDIR%

:STEP1
IF EXIST %PORTAL_WEBAPPS% GOTO STEP2
MKDIR %PORTAL_WEBAPPS%

:STEP2
IF EXIST %PORTAL_LOGS% GOTO STEP3
MKDIR %PORTAL_LOGS%

:STEP3
COPY /Y %PORTAL_ROOTDIR%\%PORTAL_NAME%.war %PORTAL_WEBAPPS%

SET PORTAL_OPTS=-Dportal.basedir=%PORTAL_BASEDIR% -Dorg.eclipse.jetty.LEVEL=INFO

SET JETTY_BASEDIR=%PORTAL_ROOTDIR%/dependency
SET JETTY_RUNNER_ARGS=--path %PORTAL_CONTEXT_PATH% --port %PORTAL_PORT% %PORTAL_WEBAPPS%\%PORTAL_NAME%.war

java %PORTAL_OPTS% -jar %JETTY_BASEDIR%\jetty-runner.jar --log %PORTAL_BASEDIR%\logs\jetty-runner.log %JETTY_RUNNER_ARGS%

:EXIT